# Generated by Django 5.0.4 on 2024-05-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
    ]
