# Generated by Django 5.0.4 on 2024-06-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_manganuevo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manganuevo',
            table='mangas_nuevos',
        ),
    ]
